name = "ride-trip-planner"
main = "api/worker.js"
compatibility_date = "2024-01-01"
routes = ["ride.incitat.io/*"]
workers_dev = false

[assets]
directory = "./public"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "ride-db"
database_id = "368b270d-9442-4674-b52f-dc21c6592dae"

[[kv_namespaces]]
binding = "SESSIONS"
id = "36162f4023ea404ab718b0b01d7622e1"

[[r2_buckets]]
binding = "ATTACHMENTS"
bucket_name = "ride-attachments"

[vars]
ENVIRONMENT = "production"
BASE_URL = "https://ride.incitat.io"
